### ISSUE TITLE
Complete okta authentication integration

### ISSUE THREAD

**Issue by KClough** [OpenHousing/hhs#19]
https://github.com/OpenHousing/hhs/blob/16b5f92cce3f4b48cd7e1faf30d86f293b2f69b6/index.js#L41

This line only checks to see if an okta token is present, not if it is valid.

Also, credentials are hardcoded in login.html file (https://github.com/OpenHousing/hhs/blob/master/static/login.html) should be moved to environment variable.

**Comment by themightychris** [comment]
Done in #21

**Comment by vykster** [comment]
Complete.
